name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #checkout the code
      - uses: actions/setup-node@v1 #setup node environment
        with:
          node-version: 16
      - run: yarn install --immutable --immutable-cache --check-cache #install dependencies
      #- run: yarn start #run the app
      - run: ^C #kill the app