name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 // checkout the code
      - uses: actions/setup-node@v1 // setup node environment
        with:
          node-version: 12
      - run: npm ci // install dependencies
      - run: npm start // run the app